[package]

name = "Tradocks"
version = "0.0.1"
authors = ["nulldata <thebreadcat@gmail.com>", "agdeveloper <andxdgu@gmail.com>"]

#[dependencies.sdl2]
#git = "https://github.com/AngryLawyer/rust-sdl2.git"
